<?php

$thinkwp_allowed_blocks = array(
	'core/block',
	'core/button',
	'core/code',
	'core/columns',
	'core/cover',
	'core/gallery',
	'core/group',
	'core/heading',
	'core/html',
	'core/image',
	'core/list',
	'core/paragraph',
	'core/preformatted',
	'core/pullquote',
	'core/quote',
	'core/separator',
	'core/shortcode',
	'core/spacer',
	'core/table',
	'core/text-columns',
	'core/video',
);
